c_stdlib_version:  # [osx]
  - "12.3"         # [osx]
MACOSX_SDK_VERSION:  # [osx]
  - "15.2"           # [osx]
c_compiler:
  - clang
cxx_compiler:
  - clangxx
c_compiler_version:    # [win or linux]
- 21                   # [win or linux]
cxx_compiler_version:  # [win or linux]
- 21                   # [win or linux]
