schema_version: 1

context:
  version: "1.1.17"

package:
  name: livekit
  version: ${{ version }}

source:
  # The build requires multiple submodule (at least two repos deep)
  - git: https://github.com/livekit/python-sdks.git
    tag: rtc-v${{ version }}
    submodules: true
    patches:
      - fix-macos-wheel-tag.patch
      - fix-struct-class-mismatch.patch

build:
  number: 0
  python:
    version_independent: true

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python ${{ python_min }}.*
        - cross-python_${{ target_platform }}
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('rust') }}
    - clangdev
    - cargo-bundle-licenses
    - cargo-auditable
    - libprotobuf
    - pkg-config
  host:
    - python      ${{ python_min }}.*
    - python-abi3 ${{ python_min }}.*
    - setuptools >=61
    - wheel
    - requests
    - pip
    - glib
    - if: linux
      then: libva
    - zlib
  run:
    - python >=${{ python_min }}
    - protobuf >=5
    - types-protobuf >=5
    - aiofiles >=24
    - numpy >=1.26

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - livekit
        - livekit.rtc
        - livekit.rtc.resources
      pip_check: true

about:
  summary: Python Real-time SDK for LiveKit
  license: Apache-2.0
  license_file:
    - LICENSE
    - livekit-rtc/rust-sdks/livekit-ffi/THIRDPARTY.yml
  homepage: https://pypi.org/project/livekit/
  repository: https://github.com/livekit/python-sdks/
  documentation: https://docs.livekit.io

extra:
  recipe-maintainers:
    - xhochy
